import { artifacts, ethers, network } from "hardhat";
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const LLM_INFERENCE_ID = BigInt("12847293847561029384");
const PARSE_WEB_ID = BigInt("12875401142070969085");
const JSON_API_ID = BigInt("13174292974160097713");

const CONTRACT_EXPORTS = [
  "TwiinFactory",
  "TwiinAgent",
  "TwiinAccount",
  "TwiinNames",
  "AgentRegistry",
  "AgentVault",
  "AgentPolicy",
  "AgentOrchestrator",
  "OracleFeed",
] as const;

const CAP = (s: string) => ethers.keccak256(ethers.toUtf8Bytes(s));

type AddressMap = {
  chainId: string;
  registry6551: string;
  twiinAgent: string;
  twiinAccountImpl: string;
  twiinNames: string;
  agentRegistry: string;
  vault: string;
  policy: string;
  oracleFeed: string;
  orchestrator: string;
  factory: string;
  mUSDC: string;
  mockRouter: string;
};

type TxMap = Record<string, string>;

function repoPath(...parts: string[]) {
  return join(__dirname, "..", "..", "..", ...parts);
}

function writeJsonFile(path: string, data: unknown) {
  writeFileSync(path, JSON.stringify(data, null, 2) + "\n");
}

async function exportAbis(sharedAbisDir: string) {
  mkdirSync(sharedAbisDir, { recursive: true });
  const indexLines = [
    "// Auto-generated by packages/contracts/scripts/deploy.ts — do not edit by hand",
  ];

  for (const name of CONTRACT_EXPORTS) {
    const artifact = await artifacts.readArtifact(name);
    writeJsonFile(join(sharedAbisDir, `${name}.json`), artifact.abi);
    indexLines.push(
      `\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    );
  }

  writeFileSync(join(sharedAbisDir, "index.ts"), indexLines.join("\n") + "\n");
}

async function assertDeploymentInvariant(condition: boolean, message: string) {
  if (!condition) throw new Error(`Deployment validation failed: ${message}`);
}

async function validateWiring(addresses: AddressMap, refs: {
  twiinAgent: Awaited<ReturnType<typeof ethers.getContractFactory>> extends never ? never : any;
  twiinNames: any;
  agentRegistry: any;
  vault: any;
  policy: any;
  oracleFeed: any;
}) {
  const {
    twiinAgent,
    twiinNames,
    agentRegistry,
    vault,
    policy,
    oracleFeed,
  } = refs;

  await assertDeploymentInvariant(
    (await twiinAgent.factory()) === addresses.factory,
    "TwiinAgent.factory mismatch",
  );
  await assertDeploymentInvariant(
    (await twiinAgent.orchestrator()) === addresses.orchestrator,
    "TwiinAgent.orchestrator mismatch",
  );
  await assertDeploymentInvariant(
    (await twiinNames.factory()) === addresses.factory,
    "TwiinNames.factory mismatch",
  );
  await assertDeploymentInvariant(
    (await twiinNames.twiinAgent()) === addresses.twiinAgent,
    "TwiinNames.twiinAgent mismatch",
  );
  await assertDeploymentInvariant(
    (await twiinNames.registry()) === addresses.agentRegistry,
    "TwiinNames.registry mismatch",
  );
  await assertDeploymentInvariant(
    (await agentRegistry.orchestrator()) === addresses.orchestrator,
    "AgentRegistry.orchestrator mismatch",
  );
  await assertDeploymentInvariant(
    (await agentRegistry.twiinNames()) === addresses.twiinNames,
    "AgentRegistry.twiinNames mismatch",
  );
  await assertDeploymentInvariant(
    (await vault.orchestrator()) === addresses.orchestrator,
    "AgentVault.orchestrator mismatch",
  );
  await assertDeploymentInvariant(
    (await policy.factory()) === addresses.factory,
    "AgentPolicy.factory mismatch",
  );
  await assertDeploymentInvariant(
    (await policy.orchestrator()) === addresses.orchestrator,
    "AgentPolicy.orchestrator mismatch",
  );
  await assertDeploymentInvariant(
    (await policy.twiinAgent()) === addresses.twiinAgent,
    "AgentPolicy.twiinAgent mismatch",
  );
  await assertDeploymentInvariant(
    (await oracleFeed.orchestrator()) === addresses.orchestrator,
    "OracleFeed.orchestrator mismatch",
  );

  const expectedNativeNames = [
    "janice",
    "web-intel",
    "somnia-oracle",
    "analysis-bot",
    "reporter-bot",
    "executor-bot",
  ];
  for (let i = 0; i < expectedNativeNames.length; i++) {
    const agent = await agentRegistry.get(i);
    await assertDeploymentInvariant(agent.isActive, `native agent ${i} inactive`);
    await assertDeploymentInvariant(
      agent.name === expectedNativeNames[i],
      `native agent ${i} name mismatch`,
    );
  }

  await assertDeploymentInvariant(
    (await agentRegistry.nextConfigId()) === 6n,
    "nextConfigId should be 6 after native seeding",
  );
}

async function main() {
  const [deployer] = await ethers.getSigners();
  const chainId = (await ethers.provider.getNetwork()).chainId;
  const keeperAddr = process.env.KEEPER_ADDRESS ?? deployer.address;
  const agentsApiAddr =
    process.env.AGENTS_API_ADDRESS ??
    "0x037Bb9C718F3f7fe5eCBDB0b600D607b52706776";

  console.log("Deploying network:", network.name);
  console.log("Deploying from:", deployer.address);
  console.log(
    "Balance:",
    ethers.formatEther(await ethers.provider.getBalance(deployer.address)),
    "STT",
  );

  const txHashes: TxMap = {};
  const captureTx = async (label: string, waitable: { deploymentTransaction?: () => any }) => {
    const tx = waitable.deploymentTransaction?.();
    if (tx) txHashes[label] = tx.hash;
  };

  console.log("\n[1/7] Deploying mocks...");
  const MockERC20F = await ethers.getContractFactory("MockERC20");
  const mUSDC = await MockERC20F.deploy("Mock USDC", "mUSDC");
  await mUSDC.waitForDeployment();
  await captureTx("mUSDC", mUSDC);

  const MockRouterF = await ethers.getContractFactory("MockUniswapV2Router02");
  const mockRouter = await MockRouterF.deploy(await mUSDC.getAddress());
  await mockRouter.waitForDeployment();
  await captureTx("mockRouter", mockRouter);
  await (await mUSDC.mint(
    await mockRouter.getAddress(),
    ethers.parseUnits("1000000", 18),
  )).wait();

  console.log("\n[2/7] Deploying local ERC-6551 Registry...");
  const RegistryF = await ethers.getContractFactory("ERC6551Registry");
  const registry6551 = await RegistryF.deploy();
  await registry6551.waitForDeployment();
  await captureTx("registry6551", registry6551);

  console.log("\n[3/7] Deploying identity layer...");
  const TwiinAgentF = await ethers.getContractFactory("TwiinAgent");
  const twiinAgent = await TwiinAgentF.deploy();
  await twiinAgent.waitForDeployment();
  await captureTx("twiinAgent", twiinAgent);

  const TwiinAccountF = await ethers.getContractFactory("TwiinAccount");
  const twiinAccountImpl = await TwiinAccountF.deploy(await twiinAgent.getAddress());
  await twiinAccountImpl.waitForDeployment();
  await captureTx("twiinAccountImpl", twiinAccountImpl);

  const TwiinNamesF = await ethers.getContractFactory("TwiinNames");
  const twiinNames = await TwiinNamesF.deploy();
  await twiinNames.waitForDeployment();
  await captureTx("twiinNames", twiinNames);

  console.log("\n[4/7] Deploying orchestration layer...");
  const AgentRegistryF = await ethers.getContractFactory("AgentRegistry");
  const agentRegistry = await AgentRegistryF.deploy();
  await agentRegistry.waitForDeployment();
  await captureTx("agentRegistry", agentRegistry);

  const AgentVaultF = await ethers.getContractFactory("AgentVault");
  const vault = await AgentVaultF.deploy();
  await vault.waitForDeployment();
  await captureTx("vault", vault);

  const AgentPolicyF = await ethers.getContractFactory("AgentPolicy");
  const policy = await AgentPolicyF.deploy();
  await policy.waitForDeployment();
  await captureTx("policy", policy);

  const OracleFeedF = await ethers.getContractFactory("OracleFeed");
  const oracleFeed = await OracleFeedF.deploy();
  await oracleFeed.waitForDeployment();
  await captureTx("oracleFeed", oracleFeed);

  const AgentOrchestratorF =
    await ethers.getContractFactory("AgentOrchestrator");
  const orchestrator = await AgentOrchestratorF.deploy(
    await registry6551.getAddress(),
    await twiinAccountImpl.getAddress(),
    await twiinAgent.getAddress(),
    await agentRegistry.getAddress(),
    await vault.getAddress(),
    await policy.getAddress(),
    await oracleFeed.getAddress(),
    agentsApiAddr,
    keeperAddr,
    deployer.address,
  );
  await orchestrator.waitForDeployment();
  await captureTx("orchestrator", orchestrator);

  console.log("\n[5/7] Deploying TwiinFactory...");
  const TwiinFactoryF = await ethers.getContractFactory("TwiinFactory");
  const factory = await TwiinFactoryF.deploy(
    await registry6551.getAddress(),
    await twiinAgent.getAddress(),
    await twiinAccountImpl.getAddress(),
    await twiinNames.getAddress(),
    await agentRegistry.getAddress(),
    await vault.getAddress(),
    await policy.getAddress(),
    await oracleFeed.getAddress(),
    await orchestrator.getAddress(),
    await mUSDC.getAddress(),
    await mockRouter.getAddress(),
  );
  await factory.waitForDeployment();
  await captureTx("factory", factory);

  console.log("\n[6/7] Wiring deferred setters...");
  await (await twiinAgent.setFactory(await factory.getAddress())).wait();
  await (await twiinNames.setFactory(await factory.getAddress())).wait();
  await (await policy.setFactory(await factory.getAddress())).wait();
  await (await twiinAgent.setOrchestrator(await orchestrator.getAddress())).wait();
  await (await twiinNames.setTwiinAgent(await twiinAgent.getAddress())).wait();
  await (await twiinNames.setRegistry(await agentRegistry.getAddress())).wait();
  await (await agentRegistry.setOrchestrator(await orchestrator.getAddress())).wait();
  await (await agentRegistry.setTwiinNames(await twiinNames.getAddress())).wait();
  await (await vault.setOrchestrator(await orchestrator.getAddress())).wait();
  await (await policy.setOrchestrator(await orchestrator.getAddress())).wait();
  await (await policy.setTwiinAgent(await twiinAgent.getAddress())).wait();
  await (await oracleFeed.setOrchestrator(await orchestrator.getAddress())).wait();

  console.log("\n[7/7] Seeding capabilities, native agents, and reserved names...");
  const capabilities = [
    { id: CAP("web.scrape"), name: "web.scrape", tier: 0, nativeOnly: false },
    {
      id: CAP("web.scrape.discord"),
      name: "web.scrape.discord",
      tier: 0,
      nativeOnly: false,
    },
    { id: CAP("json.fetch"), name: "json.fetch", tier: 0, nativeOnly: false },
    { id: CAP("llm.analyze"), name: "llm.analyze", tier: 0, nativeOnly: false },
    { id: CAP("llm.report"), name: "llm.report", tier: 0, nativeOnly: false },
    {
      id: CAP("data.specialized"),
      name: "data.specialized",
      tier: 0,
      nativeOnly: false,
    },
    {
      id: CAP("oracle.publish"),
      name: "oracle.publish",
      tier: 2,
      nativeOnly: true,
    },
    {
      id: CAP("onchain.execute"),
      name: "onchain.execute",
      tier: 2,
      nativeOnly: true,
    },
    {
      id: CAP("plan.trustless"),
      name: "plan.trustless",
      tier: 2,
      nativeOnly: true,
    },
  ];
  for (const cap of capabilities) {
    await (await agentRegistry.registerCapability(
      cap.id,
      cap.name,
      cap.tier,
      cap.nativeOnly,
    )).wait();
  }

  const nativeAgents = [
    {
      id: 0,
      name: "janice",
      somniaId: LLM_INFERENCE_ID,
      payload: "0x",
      cost: ethers.parseEther("0.24"),
      caps: [CAP("plan.trustless")],
      tier: 2,
    },
    {
      id: 1,
      name: "web-intel",
      somniaId: PARSE_WEB_ID,
      payload: "0x",
      cost: ethers.parseEther("0.33"),
      caps: [CAP("web.scrape")],
      tier: 1,
    },
    {
      id: 2,
      name: "somnia-oracle",
      somniaId: JSON_API_ID,
      payload: "0x",
      cost: ethers.parseEther("0.12"),
      caps: [CAP("json.fetch")],
      tier: 1,
    },
    {
      id: 3,
      name: "analysis-bot",
      somniaId: LLM_INFERENCE_ID,
      payload: "0x",
      cost: ethers.parseEther("0.24"),
      caps: [CAP("llm.analyze")],
      tier: 1,
    },
    {
      id: 4,
      name: "reporter-bot",
      somniaId: LLM_INFERENCE_ID,
      payload: "0x",
      cost: ethers.parseEther("0.24"),
      caps: [CAP("llm.report")],
      tier: 1,
    },
    {
      id: 5,
      name: "executor-bot",
      somniaId: LLM_INFERENCE_ID,
      payload: "0x",
      cost: ethers.parseEther("0.24"),
      caps: [CAP("onchain.execute")],
      tier: 2,
    },
  ];
  for (const a of nativeAgents) {
    await (await agentRegistry.registerNative(
      a.id,
      a.name,
      a.somniaId,
      a.payload,
      a.cost,
      a.caps,
      a.tier,
    )).wait();
  }

  const reservedNames = [
    "janice",
    "web-intel",
    "somnia-oracle",
    "analysis-bot",
    "reporter-bot",
    "executor-bot",
    "system",
    "twiin",
    "admin",
  ];
  for (const name of reservedNames) {
    await (await agentRegistry.reserveSubAgentName(name)).wait();
  }

  const addresses: AddressMap = {
    chainId: chainId.toString(),
    registry6551: await registry6551.getAddress(),
    twiinAgent: await twiinAgent.getAddress(),
    twiinAccountImpl: await twiinAccountImpl.getAddress(),
    twiinNames: await twiinNames.getAddress(),
    agentRegistry: await agentRegistry.getAddress(),
    vault: await vault.getAddress(),
    policy: await policy.getAddress(),
    oracleFeed: await oracleFeed.getAddress(),
    orchestrator: await orchestrator.getAddress(),
    factory: await factory.getAddress(),
    mUSDC: await mUSDC.getAddress(),
    mockRouter: await mockRouter.getAddress(),
  };

  await validateWiring(addresses, {
    twiinAgent,
    twiinNames,
    agentRegistry,
    vault,
    policy,
    oracleFeed,
  });

  const deploymentReceipts = await Promise.all(
    Object.values(txHashes).map((hash) => ethers.provider.getTransactionReceipt(hash)),
  );
  const minDeploymentBlock = deploymentReceipts.reduce<bigint>(
    (min, receipt) => {
      if (!receipt) return min;
      const blockNumber = BigInt(receipt.blockNumber);
      return blockNumber < min ? blockNumber : min;
    },
    BigInt(Number.MAX_SAFE_INTEGER),
  );

  const manifest = {
    _note: "Generated by packages/contracts/scripts/deploy.ts — do not edit by hand",
    network: network.name,
    chainId: addresses.chainId,
    startBlock: minDeploymentBlock.toString(),
    deployer: deployer.address,
    keeper: keeperAddr,
    agentsApi: agentsApiAddr,
    deployedAt: new Date().toISOString(),
    addresses,
    txHashes,
    capabilities: capabilities.map((cap) => ({
      id: cap.id,
      name: cap.name,
      minTrustTier: cap.tier,
      nativeOnly: cap.nativeOnly,
    })),
    nativeAgents: nativeAgents.map((agent) => ({
      configId: agent.id,
      name: agent.name,
      somniaId: agent.somniaId.toString(),
      costWei: agent.cost.toString(),
      capabilities: agent.caps,
      trustTier: agent.tier,
    })),
    reservedNames,
  };

  const contractsDeploymentsDir = repoPath("packages", "contracts", "deployments");
  const sharedDeploymentsDir = repoPath("packages", "shared", "deployments");
  const sharedAbisDir = repoPath("packages", "shared", "abis");
  mkdirSync(contractsDeploymentsDir, { recursive: true });
  mkdirSync(sharedDeploymentsDir, { recursive: true });

  await exportAbis(sharedAbisDir);
  writeJsonFile(join(contractsDeploymentsDir, `${network.name}.json`), manifest);
  writeJsonFile(join(sharedDeploymentsDir, `${network.name}.json`), manifest);
  writeJsonFile(
    repoPath("packages", "shared", "addresses.json"),
    {
      _note: "Generated by packages/contracts/scripts/deploy.ts — do not edit by hand",
      ...addresses,
    },
  );

  console.log("\nDeployment validated and exported.");
  console.log(`  contracts manifest: packages/contracts/deployments/${network.name}.json`);
  console.log(`  shared manifest:    packages/shared/deployments/${network.name}.json`);
  console.log("  shared addresses:   packages/shared/addresses.json");
  console.log("  shared ABIs:        packages/shared/abis/");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
