import { artifacts } from "hardhat";
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const CONTRACT_EXPORTS = [
  "TwiinFactory",
  "TwiinAgent",
  "TwiinAccount",
  "TwiinNames",
  "AgentRegistry",
  "AgentVault",
  "AgentPolicy",
  "AgentOrchestrator",
  "AgentRefreshCoordinator",
  "OracleFeed",
] as const;

function repoPath(...parts: string[]) {
  return join(__dirname, "..", "..", "..", ...parts);
}

function writeJsonFile(path: string, data: unknown) {
  writeFileSync(path, JSON.stringify(data, null, 2) + "\n");
}

async function main() {
  const sharedAbisDir = repoPath("packages", "shared", "abis");
  mkdirSync(sharedAbisDir, { recursive: true });

  const indexLines = [
    "// Auto-generated by packages/contracts/scripts/deploy.ts — do not edit by hand",
  ];

  for (const name of CONTRACT_EXPORTS) {
    const artifact = await artifacts.readArtifact(name);
    writeJsonFile(join(sharedAbisDir, `${name}.json`), artifact.abi);
    indexLines.push(
      `\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    );
  }

  writeFileSync(join(sharedAbisDir, "index.ts"), indexLines.join("\n") + "\n");
  console.log("Exported ABIs to packages/shared/abis/");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
