import {
  parsePayload,
  type ExternalExecuteInput,
} from "@twiin/external-kit";
import {
  formatKeyMetricEntry,
  resolveAgentDisplayName,
} from "@twiin/shared";
import type { BriefsmithEnv } from "./env";

function extractInstruction(raw: string): string {
  const match = raw.match(/^(.+?)(?:\n\n|\n)(?:Previous step outputs:|$)/s);
  if (match?.[1]?.trim()) return match[1].trim();
  return raw.slice(0, 300);
}

function extractPriorContext(raw: string): string {
  const idx = raw.indexOf("Previous step outputs:");
  if (idx !== -1) return raw.slice(idx);
  return raw;
}

function extractStepLines(context: string): { label: string; raw: string }[] {
  return context
    .split("\n")
    .filter((l) => l.startsWith("- "))
    .map((l) => {
      const colon = l.indexOf(":");
      const label = colon !== -1 ? l.slice(2, colon).trim() : "step";
      const raw = colon !== -1 ? l.slice(colon + 1).trim() : l.slice(2).trim();
      return { label, raw };
    });
}

export async function executeBriefsmith(input: ExternalExecuteInput): Promise<string> {
  const env = input.env as BriefsmithEnv;
  const parsed = parsePayload(input.payloadHex);
  const raw = parsed.raw;
  const instruction = extractInstruction(raw);
  const priorContext =
    typeof parsed.json?.priorContext === "string"
      ? parsed.json.priorContext
      : extractPriorContext(raw);

  if (env.ANTHROPIC_API_KEY) {
    try {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": env.ANTHROPIC_API_KEY,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: env.BRIEFSMITH_MODEL,
          max_tokens: 1200,
          messages: [
            {
              role: "user",
              content: [
                instruction,
                "",
                priorContext.slice(0, 8000),
              ].join("\n\n"),
            },
          ],
        }),
        signal: AbortSignal.timeout(30_000),
      });

      if (!res.ok) {
        const errText = await res.text();
        throw new Error(`Anthropic ${res.status}: ${errText.slice(0, 200)}`);
      }

      const body = (await res.json()) as {
        content?: Array<{ type?: string; text?: string }>;
      };
      const brief =
        body.content?.find((block) => block.type === "text")?.text ??
        "Brief generation returned no text.";

      return brief;
    } catch (error) {
      return fallbackBrief(env.AGENT_NAME, priorContext);
    }
  }

  return fallbackBrief(env.AGENT_NAME, priorContext);
}

function fallbackBrief(
  agentName: string,
  priorContext: string,
): string {
  const steps = extractStepLines(priorContext);
  const metrics =
    steps
      .map((s) => formatKeyMetricEntry(s.label, s.raw))
      .filter(Boolean)
      .join("\n\n") || "- No prior step data available.";

  const brief = [
    "## Executive Summary",
    `Multi-agent pipeline executed for network monitoring task. ${steps.length} sub-agents completed data collection across on-chain RPC, reactivity precompile, market price feed, and consensus validation.`,
    "",
    "## Key Metrics",
    metrics,
    "",
    "## Corroboration Notes",
    steps.length > 0
      ? "- Data independently collected from multiple sources (RPC, reactivity, CoinGecko, native validators)."
      : "- No corroboration data available.",
    "- All dispatched steps received and processed by the relay keeper without timeout.",
    "",
    "## Risks & Gaps",
    "- Brief generated in structured fallback mode (LLM synthesis unavailable).",
    "- Raw agent outputs should be reviewed for data quality before on-chain publication.",
    "",
    "## Confidence Score",
    "**65/100** — data pipeline completed but requires human review for publish-ready quality",
    "",
    "## Sources",
    steps.map((s) => `- ${resolveAgentDisplayName(s.label, s.raw)}`).join("\n") ||
      "- No sources recorded.",
    "",
    "_Generated by Twiin Agent Network_",
  ].join("\n");

  return brief;
}
