import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const CONTRACTS = [
  "TwiinFactory",
  "TwiinAgent",
  "TwiinAccount",
  "TwiinNames",
  "AgentRegistry",
  "AgentVault",
  "AgentPolicy",
  "AgentOrchestrator",
  "OracleFeed",
];

const artifactsDir = join(__dirname, "../../contracts/artifacts/src");
const abisDir = join(__dirname, "../abis");

mkdirSync(abisDir, { recursive: true });

const indexLines: string[] = [
  "// Auto-generated by scripts/copy-abis.ts — do not edit by hand",
];

for (const name of CONTRACTS) {
  const artifactPath = join(artifactsDir, `${name}.sol`, `${name}.json`);
  let artifact: { abi: unknown[] };
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf-8")) as {
      abi: unknown[];
    };
  } catch {
    throw new Error(
      `Artifact not found: ${artifactPath}\n` +
        `Run "pnpm compile" in packages/contracts first.`,
    );
  }

  writeFileSync(
    join(abisDir, `${name}.json`),
    JSON.stringify(artifact.abi, null, 2),
  );

  const constName = `${name}Abi`;
  indexLines.push(
    `\nexport const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
  );
}

writeFileSync(join(abisDir, "index.ts"), indexLines.join("\n") + "\n");

console.log(`✅ Extracted ABIs for: ${CONTRACTS.join(", ")}`);
console.log(`   → ${abisDir}/`);
